// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2rfKXm1MbCSio_1EJyyq2rKOQbY8I_0',
    appId: '1:572154506169:web:838c876bfd19bcb5ade468',
    messagingSenderId: '572154506169',
    projectId: 'my-tooth-app-13662',
    authDomain: 'my-tooth-app-13662.firebaseapp.com',
    storageBucket: 'my-tooth-app-13662.appspot.com',
    measurementId: 'G-HRBKT35PEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkPxF7i4dHGYNC9QGL6YViDg5q-l0O_Y',
    appId: '1:572154506169:android:c7219316b9c46e19ade468',
    messagingSenderId: '572154506169',
    projectId: 'my-tooth-app-13662',
    storageBucket: 'my-tooth-app-13662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOOdI-bB2ynQlXcRnovDPrPJXIrtRf2ww',
    appId: '1:572154506169:ios:8cf6b44e5c7078cdade468',
    messagingSenderId: '572154506169',
    projectId: 'my-tooth-app-13662',
    storageBucket: 'my-tooth-app-13662.appspot.com',
    iosClientId: '572154506169-adv4c281ae63776q4uthijmn19vc20tp.apps.googleusercontent.com',
    iosBundleId: 'com.example.myToothApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOOdI-bB2ynQlXcRnovDPrPJXIrtRf2ww',
    appId: '1:572154506169:ios:0d065001b2beee11ade468',
    messagingSenderId: '572154506169',
    projectId: 'my-tooth-app-13662',
    storageBucket: 'my-tooth-app-13662.appspot.com',
    iosClientId: '572154506169-ong90bm58n2aa84fc5iho8qi7oailtca.apps.googleusercontent.com',
    iosBundleId: 'com.example.myToothApp.RunnerTests',
  );
}
